- name: prepare image for workers
  include: ../create-vms/tasks/prepare-image.yaml   
  with_items: '{{ cluster.compute.workers }}'

# - name: create tpm-devices
#   include: ../create-vms/tasks/create-tpm-device.yaml
#   with_items: '{{ cluster.compute.workers }}'
#   when: cluster.use_tpm  

- name: create workers
  virt:
    command: define
    xml: '{{ lookup("template", "../create-vms/templates/vm-template.xml.j2") }}'
  with_items: '{{ cluster.compute.workers }}'

- name: start workers
  virt:
    state: running
    name: '{{ item.name }}.{{ cluster.compute.vms_domain }}'
  with_items: '{{ cluster.compute.workers }}'

- name: approve csrs
  pause: 
    prompt: |
      at this point you need to approve the csr, on a different terminal check if all the csr are present:
      oc --kubeconfig={{ workdir.install }}/auth/kubeconfig get csr
      when all the csr are present, run this command:       
      oc --kubeconfig={{ workdir.install }}/auth/kubeconfig get csr -o name | xargs oc --kubeconfig={{ workdir.install }}/auth/kubeconfig adm certificate approve 
    minutes: 10   